name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libtool autoconf automake pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev
          pip3 install --user --upgrade Cython==0.29.33 virtualenv

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          buildozer android debug
        env:
          APP_ANDROID_ACCEPT_SDK_LICENSE: "1"

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: monitor-app-apk
          path: bin/*.apk
